force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>Budget</label>
    <nameField>
        <displayFormat>BID-{000000000}</displayFormat>
        <label>Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget__c/fields/Budget_Version__c.field-meta.xml
<CustomField>
    <fullName>Budget_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Version</label>
    <referenceTo>Budget_Version__c</referenceTo>
    <relationshipLabel>Budget</relationshipLabel>
    <relationshipName>Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/Budget_Line__c.object-meta.xml
<CustomObject>
    <description>This is used for storing the budget lines against</description>
    <label>Budget Line</label>
    <nameField>
        <displayFormat>BLID-{000000000}</displayFormat>
        <label>Budget Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Budget Lines</relationshipLabel>
    <relationshipName>Budget_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Budget_Version__c.field-meta.xml
<CustomField>
    <fullName>Budget_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Version</label>
    <referenceTo>Budget_Version__c</referenceTo>
    <relationshipLabel>Budget Lines</relationshipLabel>
    <relationshipName>Budget_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Line__c/fields/Budget_Year__c.field-meta.xml
<CustomField>
    <fullName>Budget_Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Budget Year</label>
    <referenceTo>Budget_Year__c</referenceTo>
    <relationshipLabel>Budget Lines</relationshipLabel>
    <relationshipName>Budget_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Budget_Version__c/Budget_Version__c.object-meta.xml
<CustomObject>
    <label>Budget Version</label>
    <nameField>
        <label>Version</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Version</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Year__c/Budget_Year__c.object-meta.xml
<CustomObject>
    <description>This is used to specify the year start / end dates for the given year</description>
    <label>Budget Year</label>
    <nameField>
        <label>Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budget Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BudgetTriggerAfterInsert.cls
/**
 * @description       : budget trigger after insert process
 * @author            : daniel@hyphen8.com
 * @group             : 
 * @last modified on  : 04-30-2021
 * @last modified by  : daniel@hyphen8.com
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   04-30-2021   daniel@hyphen8.com   Initial Version
**/
public with sharing class BudgetTriggerAfterInsert {
    
    public static void afterInsert(List<Budget__c> currentRecords){

        List<Budget_Year__c> budgetYears = BudgetTriggerHelper.getBudgetYears();

        List<Budget_Line__c> linesToInsert = new List<Budget_Line__c>();

        for(Budget__c budget:currentRecords){
            for(Budget_Year__c year:budgetYears){
                Budget_Line__c budgetLine = new Budget_Line__c();
                budgetLine.Budget__c = budget.Id;
                budgetLine.Budget_Version__c = budget.Budget_Version__c;
                budgetLine.Budget_Year__c = year.Id;
                linesToInsert.add(budgetLine);
            }
        }

        database.insert(linesToInsert);
        
    }
}